name: Aperture
options:
  bundleIdPrefix: com.aperture
  developmentLanguage: en
  deploymentTarget:
    macOS: "13.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  findCarthageFrameworks: false
  minimumXcodeGenVersion: 2.44.0

packages:
  Onboarding:
    url: https://github.com/Aayush9029/Onboarding
    from: 1.0.0
  SFSafeSymbols:
    url: https://github.com/SFSafeSymbols/SFSafeSymbols
    from: 5.0.0
  AppInformation:
    url: https://github.com/Aayush9029/AppInformation
    from: 1.0.0
  WelcomeWindow:
    url: https://github.com/Aayush9029/WelcomeWindow
    from: 1.0.0
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.0
  Engine:
    url: https://github.com/Aayush9029/Engine
    from: 1.0.0
  AppState:
    url: https://github.com/Aayush9029/AppState
    from: 1.0.0

targets:
  Aperture:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: Aperture
        excludes:
          - "**/.DS_Store"
    info:
      path: Aperture/Info.plist
      properties:
        CFBundleName: Aperture
        CFBundleDisplayName: Aperture
        CFBundleIdentifier: com.aperture.app
        CFBundleVersion: "1.0.0"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "13.0"
        NSPrincipalClass: NSApplication
        NSMainStoryboardFile: ""
        NSSupportsAutomaticTermination: true
        NSSupportsSuddenTermination: true
        NSHighResolutionCapable: true
        NSScreenCaptureUsageDescription: "Aperture needs screen recording permission to capture your screen."
        MetalCaptureEnabled: true
        CFBundleDocumentTypes:
          - CFBundleTypeName: Video
            CFBundleTypeRole: Editor
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - public.movie
              - public.mpeg-4
              - com.apple.quicktime-movie
              - public.avi
              - com.compuserve.gif
        UTImportedTypeDeclarations:
          - {}
    entitlements:
      path: Aperture/Aperture.entitlements
      properties:
        com.apple.developer.aps-environment: development
        com.apple.security.app-sandbox: true
        com.apple.security.temporary-exception.mach-lookup.global-name:
          - com.apple.screencapture.interactive
    settings:
      base:
        PRODUCT_NAME: Aperture
        PRODUCT_BUNDLE_IDENTIFIER: com.aperture.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        ENABLE_HARDENED_RUNTIME: true
        MACOSX_DEPLOYMENT_TARGET: "13.0"
        SWIFT_VERSION: "5.9"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Aperture/Info.plist
        CODE_SIGN_ENTITLEMENTS: Aperture/Aperture.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        COMBINE_HIDPI_IMAGES: true
        SWIFT_EMIT_LOC_STRINGS: true
        SWIFT_OBJC_BRIDGING_HEADER: ""
        OTHER_LDFLAGS:
          - "-framework AVFoundation"
          - "-framework ScreenCaptureKit"
          - "-framework CoreMedia"
          - "-framework AVKit"
          - "-framework Accelerate"
          - "-framework Metal"
          - "-framework CoreAudio"
          - "-framework AudioToolbox"
      configs:
        Debug:
          SWIFT_ACTIVE_COMPILATION_CONDITIONS:
            - DEBUG
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          GCC_OPTIMIZATION_LEVEL: "0"
          ONLY_ACTIVE_ARCH: true
          ENABLE_TESTABILITY: true
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: wholemodule
          GCC_OPTIMIZATION_LEVEL: "s"
          ENABLE_TESTABILITY: false
    dependencies:
      - package: Onboarding
      - package: SFSafeSymbols
      - package: AppInformation
      - package: WelcomeWindow
      - package: Pow
      - package: Engine
      - package: AppState
      - sdk: AVFoundation.framework
      - sdk: ScreenCaptureKit.framework
      - sdk: CoreMedia.framework
      - sdk: AVKit.framework
      - sdk: Accelerate.framework
      - sdk: Metal.framework
      - sdk: CoreAudio.framework
      - sdk: AudioToolbox.framework
      - sdk: Cocoa.framework
      - sdk: SwiftUI.framework
      - sdk: Combine.framework
      - sdk: UniformTypeIdentifiers.framework
    scheme:
      testTargets: []
      configVariants:
        - Debug
        - Release
      gatherCoverageData: false
      disableMainThreadChecker: false
      stopOnEveryMainThreadCheckerIssue: false

schemes:
  Aperture:
    build:
      targets:
        Aperture: all
    run:
      config: Debug
      commandLineArguments: {}
      environmentVariables: {}
    test:
      config: Debug
      gatherCoverageData: false
      commandLineArguments: {}
      environmentVariables: {}
    profile:
      config: Release
      commandLineArguments: {}
      environmentVariables: {}
    analyze:
      config: Debug
    archive:
      config: Release
